# Evaluation Dataset

## Libraries

In [ ]:
import json
import pandas as pd
from openai import OpenAI
from dotenv import load_dotenv
from pathlib import Path

load_dotenv()
client = OpenAI()

## Data Load

In [ ]:
def load_json_to_dataframe(folder: str) -> pd.DataFrame:
    dfs = []

    for file in Path(folder).glob("*.json"):
        with open(file, "r", encoding="utf-8") as f:
            raw = f.read().strip()

            try:
                records = json.loads(raw)
            except json.JSONDecodeError:
                records = [json.loads(line) for line in raw.splitlines() if line.strip()]

        if isinstance(records, dict):
            records = [records]

        temp_df = pd.DataFrame(records)

        if temp_df.empty:
            continue

        if "content" in temp_df.columns:
            temp_df["text"] = temp_df["content"]

        # ensure required columns exist
        if "url" not in temp_df.columns or "text" not in temp_df.columns:
            continue

        # restore schema
        temp_df["type"] = temp_df.get("type", "chunked")
        temp_df["depth"] = temp_df.get("depth", None)
        temp_df["file"] = file.stem

        temp_df = temp_df[~temp_df["url"].astype(str).str.contains("qa://", na=False)]

        dfs.append(temp_df[["url", "type", "depth", "text", "file"]])

    return pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()

In [26]:
data_bc = load_json_to_dataframe("/Users/antoniooliveira/Documents/GitHub/IAPMEI-chatbot-v3/data/01_extracted")
data_ac = load_json_to_dataframe("/Users/antoniooliveira/Documents/GitHub/IAPMEI-chatbot-v3/data/03_chunked/c600_60")

In [27]:
data_bc.head()

,url,type,depth,text,file
0,https://algarve.portugal2030.pt/,html,0,Programas do Portugal 2030 PESSOAS 2030 COMPET...,algarve2030
1,https://algarve.portugal2030.pt/ajuda-artigos/,html,1,Programas do Portugal 2030 PESSOAS 2030 COMPET...,algarve2030
2,https://algarve.portugal2030.pt/eventos/,html,1,Programas do Portugal 2030 PESSOAS 2030 COMPET...,algarve2030
3,https://algarve.portugal2030.pt/noticias/,html,1,Programas do Portugal 2030 PESSOAS 2030 COMPET...,algarve2030
4,https://algarve.portugal2030.pt/o-portugal-2030/,html,1,Programas do Portugal 2030 PESSOAS 2030 COMPET...,algarve2030

In [28]:
data_ac.head()

,url,type,depth,text,file
0,https://algarve.portugal2030.pt/,chunked,None,Fonte: algarve.portugal2030.pt: Algarve 2030 A...,algarve2030
1,https://algarve.portugal2030.pt/,chunked,None,Fonte: algarve.portugal2030.pt: . Saiba mais E...,algarve2030
2,https://algarve.portugal2030.pt/,chunked,None,Fonte: algarve.portugal2030.pt: . “A água é um...,algarve2030
3,https://algarve.portugal2030.pt/ajuda-artigos/,chunked,None,Fonte: Ajuda artigos: Ajuda Precisa de ajuda? ...,algarve2030
4,https://algarve.portugal2030.pt/ajuda-artigos/,chunked,None,Fonte: Ajuda artigos: . Limpar filtros Ordenar...,algarve2030

# Evaluation Dataset Creation

In [29]:
dfs = {
    file_name: df_file.copy()
    for file_name, df_file in data_ac.groupby("file")
}

In [30]:
dfs.keys()

dict_keys(['alentejo2030', 'algarve2030', 'centro2030', 'compete2030', 'iapmei_website', 'lisboa2030', 'norte2030', 'portugal2030'])

In [27]:
def generate_qa_from_df(
    df: pd.DataFrame,
    text_column: str,
    model: str = "gpt-4o-mini",
    n_questions: int = 5,
    max_chars: int = 6000
):
    """
    Receives a DataFrame with text and returns n question–answer pairs in JSON format.
    """

    # 1. Prepare text (truncate to avoid context overflow)
    text = "\n\n".join(df[text_column].dropna().astype(str).tolist())
    text = text[:max_chars]

    # 2. Prompt
    prompt = f"""
        És um assistente que cria perguntas e respostas com base na informação fornecida. 
        Sê sempre claro na questão que colocas, garantindo sempre que tem informação suficiente 
        para que seja possível obter uma resposta. Lembra-te de que, no futuro, a busca pela
        resposta será feita relativamente a todos os programas.
        
        Regras:
        - Gera exatamente {n_questions} perguntas e respostas
        - As perguntas devem ser claras e relevantes
        - As respostas devem basear-se apenas na informação disponível e ser o mais completas possível
        - Responde APENAS em JSON válido sempre, independentemente de tudo o resto.
        
        Texto:
        \"\"\"
        {text}
        \"\"\"
        """

    # 3. Call model
    response = client.chat.completions.create(
        model=model,
        messages=[{"role": "system", "content": prompt}],
        temperature=0.2,
        response_format={"type": "json_object"}
    )


    # 4. Parse JSON safely
    content = response.choices[0].message.content.strip()

    try:
        qa = json.loads(content)
    except json.JSONDecodeError as e:
        raise ValueError(f"Model did not return valid JSON:\n{content}") from e

    return qa

In [28]:
all_qa = {}

for file_name, df in dfs.items():
    qa_pairs = generate_qa_from_df(
        df=df,
        text_column="content"
    )
    all_qa[file_name] = qa_pairs

In [12]:
[q["questions"] for q in all_qa["portugal2030"]["questions"]]

['O que é o Portugal 2030 e qual é o seu objetivo?',
 'Quantos milhões de euros já foram pagos aos beneficiários do Portugal 2030?',
 'Quando e onde ocorreu a Mostra dos Fundos Europeus?',
 'Quais são os programas que compõem o Portugal 2030?',
 'Como os interessados podem entrar em contato com a Linha dos Fundos para esclarecer dúvidas?']

In [29]:
all_qa

{'alentejo2030': {'perguntas_e_respostas': [{'pergunta': 'O que é o programa Alentejo 2030?',
    'resposta': 'O Alentejo 2030 é um programa que visa transformar vidas na região do Alentejo, impulsionando a inovação, a sustentabilidade e o crescimento. O programa também oferece oportunidades para beneficiar dos Fundos Europeus disponíveis.'},
   {'pergunta': 'Quais são algumas das novas prioridades específicas integradas na reprogramação do Alentejo 2030?',
    'resposta': 'As novas prioridades incluem a Defesa, a Água, a Habitação a preços acessíveis e sustentável, e as Competências para a descarbonização. Estas áreas focam em tecnologias de dupla utilização, gestão sustentável da água, acesso à habitação e educação voltada para a transição climática.'},
   {'pergunta': 'Quando foi aprovada a reprogramação do Alentejo 2030 pela Comissão Europeia?',
    'resposta': 'A reprogramação do Alentejo 2030 foi aprovada pela Comissão Europeia no dia 15 de dezembro de 2025.'},
   {'pergunta': 'Quais são os principais domínios de investimento priorizados na reprogramação do Alentejo 2030?',
    'resposta': 'Os principais domínios de investimento incluem Investigação, inovação e adoção de tecnologias avançadas, Digitalização, Eficiência energética, Economia circular, Mobilidade urbana sustentável, Educação, Saúde, Inclusão social e Cultura.'},
   {'pergunta': 'Qual é o impacto esperado da reprogramação do Alentejo 2030 na região?',
    'resposta': 'A reprogramação do Alentejo 2030 visa reforçar a resposta da região aos desafios económicos, sociais, ambientais e territoriais, contribuindo para um desenvolvimento mais sustentável, inclusivo e resiliente, alinhado com as prioridades europeias e nacionais.'}]},
 'algarve2030': {'perguntas_respostas': [{'pergunta': 'Qual é o objetivo principal do Programa Algarve 2030?',
    'resposta': 'O Programa Algarve 2030 destina-se a promover a competitividade e diversificação da economia e a sustentabilidade regional, valorizando o território e as pessoas.'},
   {'pergunta': 'Quais são algumas das iniciativas relacionadas com a gestão da água no Algarve 2030?',
    'resposta': 'As iniciativas incluem a redução de perdas nas redes urbanas de água, reabilitação de infraestruturas obsoletas, prevenção e mitigação da intrusão salina, reutilização de águas residuais tratadas para fins não potáveis, e a expansão e modernização das redes de saneamento.'},
   {'pergunta': 'Qual é o montante total de candidaturas recebidas para o ciclo urbano da água até 28 de novembro de 2025?',
    'resposta': 'Até 28 de novembro de 2025, foram recebidas 25 candidaturas que totalizam um investimento de mais de 100 milhões de euros.'},
   {'pergunta': 'Qual é a taxa média de cofinanciamento dos investimentos no ciclo urbano da água pelo Fundo Europeu de Desenvolvimento Regional (FEDER)?',
    'resposta': 'A taxa média de cofinanciamento dos investimentos no ciclo urbano da água pelo FEDER é de 60%.'},
   {'pergunta': 'Como o Programa Algarve 2030 está alinhado com as políticas de resiliência climática?',
    'resposta': 'Os investimentos do Programa Algarve 2030 estão alinhados com os compromissos de resiliência climática e transição ecológica, promovendo uma gestão mais eficiente e resiliente dos recursos hídricos, especialmente no contexto de escassez hídrica e alterações climáticas.'}]},
 'centro2030': {'perguntas_respostas': [{'pergunta': 'Qual é o objetivo principal do Programa Centro 2030?',
    'resposta': 'O Programa Centro 2030 tem como objetivo promover a competitividade da economia, a sustentabilidade ambiental e a valorização do território e das pessoas na região Centro de Portugal, no contexto da Política de Coesão da União Europeia.'},
   {'pergunta': 'Quais áreas foram priorizadas na reprogramação do Programa Centro 2030 aprovada pela Comissão Europeia?',
    'resposta': 'A reprogramação do Programa Centro 2030 prioriza a habitação (social e a preços acessíveis), apoio a projetos de tecnologias críticas e projetos empresariais na área da defesa.'},
   {'pergunta': 'Qual é o montante de financiamento alocado para a habitação na reprogramação do Centro 2030?',
    'resposta': 'Quase 200 milhões de euros foram alocados para investimento na ampliação do parque público de habitação, promovendo a renovação de edifícios devolutos ou vagos para oferta pública de habitação sustentável e acessível.'},
   {'pergunta': 'Como o Programa Centro 2030 está alinhado com as novas prioridades europeias?',
    'resposta': 'O Programa Centro 2030 foi adaptado para alinhar-se com as novas prioridades europeias, respondendo a desafios estratégicos como competitividade, descarbonização, defesa e segurança, habitação e água, em conformidade com as exigências da regulamentação europeia.'},
   {'pergunta': 'Qual é a abordagem do Programa Centro 2030 em relação à fraude e corrupção?',
    'resposta': 'O Programa Centro 2030 adota uma política de tolerância zero à fraude, alinhando-se com os Regulamentos Europeus e a Estratégia Nacional Antifraude (ENAF) para garantir a gestão eficaz e transparente dos fundos europeus, protegendo-os contra fraudes e irregularidades.'}]},
 'compete2030': {'perguntas_respostas': [{'pergunta': 'Qual é o objetivo principal do programa COMPETE 2030?',
    'resposta': 'O objetivo principal do programa COMPETE 2030 é tornar Portugal mais competitivo, sustentável e inclusivo, através da promoção da digitalização, investigação e inovação, descarbonização, energias renováveis, eficiência energética, e inclusão social.'},
   {'pergunta': 'Quais são os três pilares principais do programa COMPETE 2030?',
    'resposta': 'Os três pilares principais do programa COMPETE 2030 são: 1) Portugal + Competitivo, que foca na digitalização, investigação e inovação; 2) Portugal + Verde, que visa a descarbonização e a promoção de energias renováveis; e 3) Portugal + Social, que se concentra na qualificação de jovens e adultos e na inclusão social.'},
   {'pergunta': 'Como o programa COMPETE 2030 apoia as PME?',
    'resposta': 'O programa COMPETE 2030 apoia as PME através de iniciativas que promovem a digitalização, a investigação e a inovação, além de apoiar projetos de descarbonização e a adaptação de trabalhadores e empresas às mudanças, aumentando suas competências.'},
   {'pergunta': 'Qual é a data de encerramento do programa COMPETE 2030?',
    'resposta': 'O programa COMPETE 2030 está previsto para encerrar em 9 de dezembro de 2025.'},
   {'pergunta': 'O que é a Rede de Fornecedores Inovadores e como pode beneficiar as empresas?',
    'resposta': 'A Rede de Fornecedores Inovadores é uma medida que visa reforçar a integração das empresas portuguesas em cadeias de valor globais, potenciando sua competitividade internacional. As empresas podem participar através de consórcios inovadores com o apoio do COMPETE 2030 e dos Programas Regionais do Portugal 2030.'}]},
 'iapmei': {'perguntas_respostas': [{'pergunta': 'Quais são os programas de empreendedorismo qualificado e inovador disponíveis no IAPMEI?',
    'resposta': 'Os programas de empreendedorismo qualificado e inovador disponíveis no IAPMEI incluem o StartUP Voucher e o StartUP Visa.'},
   {'pergunta': 'O que é a Certificação PME e quais distinções estão associadas a ela?',
    'resposta': 'A Certificação PME é um processo que permite que empresas sejam reconhecidas como micro, pequenas ou médias empresas. As distinções associadas incluem PME Líder e PME Excelência.'},
   {'pergunta': 'Quais são os principais objetivos do Mecanismo de Alerta Precoce (MAP)?',
    'resposta': 'O Mecanismo de Alerta Precoce (MAP) tem como objetivo apoiar a reestruturação e revitalização de negócios em dificuldades, oferecendo ferramentas como o Autodiagnóstico Financeiro e mecanismos de revitalização.'},
   {'pergunta': 'Como o IAPMEI apoia as empresas na transição digital e sustentabilidade?',
    'resposta': 'O IAPMEI oferece formação e ferramentas para apoiar a transição digital e a sustentabilidade das empresas, incluindo informações sobre licenciamento industrial e práticas de economia circular.'},
   {'pergunta': 'Quais são as linhas de apoio à tesouraria disponíveis para as empresas em 2024?',
    'resposta': 'Em 2024, as linhas de apoio à tesouraria disponíveis incluem candidaturas contratadas que somam mais de 1.000, com um montante global aproximado de 37 milhões de euros.'}]},
 'lisboa2030': {'perguntas_respostas': [{'pergunta': 'Qual é o objetivo principal do Programa Lisboa 2030?',
    'resposta': 'O Programa Lisboa 2030 destina-se a promover a competitividade da economia, a sustentabilidade ambiental e a valorização do território e das pessoas na região de Lisboa.'},
   {'pergunta': 'O que é o Espaço de Descoberta Empreendedora (EDE) e qual foi seu propósito na última sessão realizada?',
    'resposta': 'O Espaço de Descoberta Empreendedora (EDE) é um evento que reúne atores relevantes do ecossistema regional de inovação para impulsionar oportunidades no âmbito da Plataforma de Tecnologias Estratégicas para a Europa (STEP). Na última sessão, realizada em 27 de novembro, o objetivo foi acelerar oportunidades STEP.'},
   {'pergunta': 'Quais foram as atualizações mais recentes no Aviso MPr-2025-14 sobre Internacionalização PME?',
    'resposta': 'As atualizações no Aviso MPr-2025-14 incluem a alteração do prazo para início do investimento, que agora é de 90 dias após a apresentação da candidatura, e esclarecimentos sobre a transferência do incentivo para empresas nos projetos do PT 2020.'},
   {'pergunta': 'Quais são os temas em destaque discutidos no encontro do Espaço de Descoberta Empreendedora?',
    'resposta': 'Os temas em destaque no encontro incluíram o enquadramento dos Fundos Europeus no PT 2030, investimentos em curso e reprogramação, prioridades estratégicas, nova tipologia STEP, oportunidades futuras com um calendário indicativo de avisos e networking para troca de contactos e exploração de parcerias.'},
   {'pergunta': 'Quem presidiu a última sessão do Espaço de Descoberta Empreendedora e qual foi sua mensagem principal?',
    'resposta': 'A Presidente da CCDR LVT, Arquiteta Teresa Almeida, presidiu à sessão e destacou a relevância do encontro EDE na reafirmação da região de Lisboa como um polo estratégico de inovação.'}]},
 'norte2030': {'perguntas_respostas': [{'pergunta': 'Qual é o objetivo principal do programa NORTE 2030?',
    'resposta': 'O programa NORTE 2030 visa impulsionar o desenvolvimento estratégico e sustentável da Região Norte, potenciando os recursos endógenos, a qualidade do tecido económico e a capacidade dos sistemas de inovação e criatividade.'},
   {'pergunta': 'Quais são algumas das áreas de investimento do programa NORTE 2030?',
    'resposta': 'O programa NORTE 2030 investe em várias áreas, incluindo saúde, cultura, património, ciência e inovação. Por exemplo, foram aprovados 124 projetos culturais e patrimoniais e foram alocados 57 milhões de euros para ciência e inovação.'},
   {'pergunta': 'Como o programa NORTE 2030 apoia as pequenas e médias empresas (PME)?',
    'resposta': 'O programa NORTE 2030 destaca o papel central das PME na transformação económica da Região Norte, promovendo uma cultura de inovação que deve ser transversal a todo o tecido empresarial. Além disso, foram discutidas estratégias para reforçar a capacidade de inovação das PME em tempos de disrupção global.'},
   {'pergunta': "O que foi abordado na sessão 'Empowering Regional Innovation Ecosystems' em Bruxelas?",
    'resposta': "Na sessão 'Empowering Regional Innovation Ecosystems', foram debatidas estratégias para fortalecer a capacidade de inovação das PME, apresentando modelos de financiamento inter-regional e soluções tecnológicas como Inteligência Artificial e Internet das Coisas para melhorar a resiliência das cadeias de abastecimento."},
   {'pergunta': 'Como as pessoas podem se manter informadas sobre o programa NORTE 2030?',
    'resposta': 'As pessoas podem se inscrever na newsletter do NORTE 2030 para receber novidades e informações úteis sobre o programa diretamente em seu email, concordando com os Termos e Condições ao se inscrever.'}]},
 'portugal2030': {'perguntas_respostas': [{'pergunta': 'O que é o Portugal 2030?',
    'resposta': 'O Portugal 2030 é um programa que implementa o Acordo de Parceria entre Portugal e a Comissão Europeia, destinado a aplicar 23 mil milhões de euros dos fundos europeus em projetos que estimulem e desenvolvam a economia portuguesa entre 2021 e 2027.'},
   {'pergunta': 'Quantos fundos europeus suportam o Portugal 2030 e qual é o montante total?',
    'resposta': 'O Portugal 2030 é suportado por cinco fundos europeus, com um montante total de 23 mil milhões de euros.'},
   {'pergunta': 'Quais foram os resultados financeiros até agora do Portugal 2030?',
    'resposta': 'Até agora, o Portugal 2030 já pagou mais de 3,3 mil milhões de euros aos beneficiários, com 30,4% do fundo aprovado.'},
   {'pergunta': 'O que aconteceu na Mostra dos Fundos Europeus em Coimbra?',
    'resposta': 'Na Mostra dos Fundos Europeus em Coimbra, que ocorreu em dezembro, foram anunciados os vencedores da primeira edição dos Prémios dos Fundos Europeus e houve uma partilha de conhecimento e inovação entre centenas de participantes.'},
   {'pergunta': 'Como posso obter apoio técnico sobre o Balcão dos Fundos?',
    'resposta': 'Para obter apoio técnico sobre o Balcão dos Fundos, você pode entrar em contato através do telefone 800 10 35 10 (gratuito em Portugal) ou enviar um e-mail para linhadosfundos@linhadosfundos.pt. O suporte está disponível todos os dias úteis, entre as 9h e as 18h.'}]}}

In [ ]:
with open("evaluation/evaluation_dataset_v4.json", "w", encoding="utf-8") as f:
    json.dump(
        all_qa,
        f,
        ensure_ascii=False, 
        indent=2             
    )